<h1><center><font size = '8'>Data Science Tools 2: Assignment 1</font></center></h1>
<h1><center><font size = '5'>Author: Zach Chase</font></center></h1>

In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer as lb, StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

# Question 1
## Part a
Read the boston dataset csv files provided for this assignment into Python (you can use pd.read_csv()). The boston datasets are boston_weather_1, boston_weather_2, boston_weather_3, boston_weather_4, and more_weather_variables, then assign the datasets to a DataFrame variable called boston_1, boston_2, boston_3, boston_4, and more_variables, respectively. Combine or concatenate the DataFrames, boston_1, boston_2, boston_3, and boston_4 and assign the results to a DataFrame called combined_boston. These four datasets should be combined vertically since they have the same variable names, such that boston_1 is stacked on top of boston_2, and the result is stacked on top of boston_3, and the result is further stacked on top of boston_4. Horizontally merge, join or concatenate the combined_boston and more_variables DataFrames and assign the results to a DataFrame called boston_data. Print the first five rows of the boston_data, and the last five rows of the boston_data. Also print out the shape of the boston_data. 

In [2]:
# Load the csv files into Pandas DataFrames
boston_1 = pd.read_csv("boston_weather_1.csv")
boston_2 = pd.read_csv("boston_weather_2.csv")
boston_3 = pd.read_csv("boston_weather_3.csv")
boston_4 = pd.read_csv("boston_weather_4.csv")
more_variables = pd.read_csv("more_weather_variables.csv")

# Stack boston 1, 2, 3, and 4 vertically
combined_boston = pd.concat([boston_1, boston_2, boston_3, boston_4]).reset_index()
combined_boston = combined_boston.drop(columns=['index'])

# Horizontally merge combined_boston and more_variables
boston_data = pd.merge(combined_boston, more_variables, left_index=True, right_index=True)

In [3]:
# Print first 5 rows
boston_data.head()

Month  Year  LowTemp  HighTemp  WarmestMin  ColdestHigh  AveMin  AveMax  \
0      1  1920     -8.0      48.0        37.0         12.0    12.5    29.5   
1      2  1920     -7.0      52.0        34.0         16.0    20.6    34.6   
2      3  1920     10.0      72.0        45.0         25.0    30.5    48.0   
3      4  1920     26.0      67.0        46.0         37.0    38.0    52.1   
4      5  1920     36.0      86.0        61.0         45.0    47.5    61.8   

   meanTemp  TotPrecip TotSnow  Max24hrPrecip Max24hrSnow  
0      21.0       2.72    24.8           0.74         6.7  
1      27.6       4.11    32.5           1.01        12.2  
2      39.3       3.72      11           1.15           6  
3      45.1       5.68       2           1.19           2  
4      54.6       5.26       0           3.23           0

In [4]:
# Print last 5 rows
boston_data.tail()

Month  Year  LowTemp  HighTemp  WarmestMin  ColdestHigh  AveMin  AveMax  \
1135      8  2014     58.0      91.0        70.0         69.0    63.2    78.4   
1136      9  2014     46.0      93.0        72.0         56.0    58.3    74.2   
1137     10  2014     39.0      81.0        61.0         52.0    49.7    63.0   
1138     11  2014     23.0      66.0        48.0         34.0    35.5    49.5   
1139     12  2014     18.0      64.0        44.0         29.0    32.8    43.7   

      meanTemp  TotPrecip TotSnow  Max24hrPrecip Max24hrSnow  
1135      70.8       1.75       0           1.06           0  
1136      66.2       0.70       0           0.22           0  
1137      56.4       5.83       0           2.25           0  
1138      42.5       5.27     2.6           1.64         2.3  
1139      38.3       6.56     0.3           2.90         0.3

In [5]:
# Print shape
boston_data.shape

(1140, 13)

## Part b
Check the boston_data to verify how many missing data points exist under each column. 

In [87]:
boston_data.isna().sum()

Month            0
Year             0
LowTemp          6
HighTemp         5
WarmestMin       6
ColdestHigh      9
AveMin           3
AveMax           6
meanTemp         0
TotPrecip        0
TotSnow          0
Max24hrPrecip    0
Max24hrSnow      0
dtype: int64

## Part c
Drop the rows or instances that contain any missing data. Assign the resulting DataFrame to a variable called clean_boston_data. Note that this is only one way of dealing with missing data and cases with missing data are usually used if you have sufficient sample size. Check for missing data again to ensure there is no missing data in the  clean_boston_data. Print the shape of the clean_boston_data

In [9]:
clean_boston_data = boston_data.dropna()
clean_boston_data.isna().sum()

Month            0
Year             0
LowTemp          0
HighTemp         0
WarmestMin       0
ColdestHigh      0
AveMin           0
AveMax           0
meanTemp         0
TotPrecip        0
TotSnow          0
Max24hrPrecip    0
Max24hrSnow      0
dtype: int64

In [10]:
clean_boston_data.shape

(1112, 13)

## Part d
Format all the column names to lowercase and include underscore between column 
names that consist of two words. For example, meanTemp should become mean_temp, 
and Max24hrPrep can become max_24hr_prep, and HighTemp becomes high_temp, etc. 
Reassign the DataFrame with the formatted column names to the same variable, 
clean_boston_data. Print or output the columns of the clean_boston_data

In [11]:
new_columns = ['month', 'year', 'low_temp', 'high_temp', 'warmest_min',
              'coldest_high', 'ave_min', 'ave_max', 'mean_temp', 'tot_precip', 'tot_snow',
              'max_24hr_precip', 'max_24hr_snow']

clean_boston_data.columns = new_columns
print(clean_boston_data.columns)

Index(['month', 'year', 'low_temp', 'high_temp', 'warmest_min', 'coldest_high',
       'ave_min', 'ave_max', 'mean_temp', 'tot_precip', 'tot_snow',
       'max_24hr_precip', 'max_24hr_snow'],
      dtype='object')


## Part e
Select or slice all data from the clean_boston_data DataFrame, except the data where the 
Year is 1930. You can call this subset data excluding_1930. Using the excluding_1930 
DataFrame, output the first 20 unique values in the Year column.  

In [12]:
# Get data where the year is not 1930
excluding_1930 = clean_boston_data[clean_boston_data['year'] != 1930]

# Output the first 20 unique values in the year column
list(set(excluding_1930['year']))[:20]

[1920,
 1921,
 1922,
 1923,
 1924,
 1925,
 1926,
 1927,
 1928,
 1929,
 1931,
 1932,
 1933,
 1934,
 1935,
 1936,
 1937,
 1938,
 1939,
 1940]

## Part f
Select the data from the clean_boston_data where the Year is and 1995 AND the 
high_temp is greater than or equal to 90. Output or display the whole selected data. Here, 
you don’t have to assign it to any variable, but you could if you want to. 

In [108]:
clean_boston_data[(clean_boston_data['year'] == 1995) & (clean_boston_data['high_temp'] >= 90)]

month  year  low_temp  high_temp  warmest_min  coldest_high  ave_min  \
905      6  1995      53.0       95.0         73.0          61.0     60.2   
906      7  1995      59.0      100.0         75.0          67.0     67.1   
907      8  1995      55.0       96.0         72.0          66.0     64.1   

     ave_max  mean_temp  tot_precip tot_snow  max_24hr_precip max_24hr_snow  
905     77.0       68.6        1.55        0             0.53             0  
906     84.6       75.9        2.06        0             0.88             0  
907     81.5       72.8        0.82        0             0.63             0

## Part g
Select the data from the clean_boston_data where the Year is and 1995 OR the 
high_temp is greater than 89. Output or print the first 20 rows of the selected data. Here, 
you don’t have to assign it to any variable, but you could if you want to. 

In [111]:
clean_boston_data[(clean_boston_data['year'] == 1995) | (clean_boston_data['high_temp'] > 89)].head(20)

month  year  low_temp  high_temp  warmest_min  coldest_high  ave_min  \
6       7  1920      56.0       90.0         71.0          65.0     63.4   
7       8  1920      56.0       93.0         74.0          69.0     65.2   
16      5  1921      41.0       93.0         70.0          48.0     50.0   
19      8  1921      55.0       92.0         72.0          69.0     61.5   
20      9  1921      53.0       93.0         75.0          64.0     60.1   
29      6  1922      52.0       92.0         72.0          59.0     60.8   
30      7  1922      58.0       93.0         72.0          64.0     64.4   
31      8  1922      54.0       93.0         72.0          65.0     63.4   
41      6  1923      47.0       96.0         74.0          53.0     59.6   
42      7  1923      56.0       94.0         72.0          62.0     62.2   
43      8  1923      51.0       94.0         74.0          63.0     60.5   
53      6  1924      48.0       90.0         68.0          58.0     58.2   
54      7  1924      58.0       95.0         73.0          68.0     64.8   
55      8  1924      56.0       98.0         75.0          68.0     64.4   
56      9  1924      44.0       90.0         71.0          59.0     54.4   
65      6  1925      53.0      100.0         80.0          59.0     61.1   
66      7  1925      54.0       95.0         73.0          66.0     64.1   
67      8  1925      50.0       92.0         70.0          67.0     62.3   
68      9  1925      41.0       90.0         72.0          56.0     56.0   
78      7  1926      56.0      103.0         75.0          64.0     62.6   

    ave_max  mean_temp  tot_precip tot_snow  max_24hr_precip max_24hr_snow  
6      81.4       72.4        1.56        0             0.76             0  
7      78.9       72.0        2.32        0             1.00             0  
16     66.1       58.0        3.63        0             1.82             0  
19     77.7       69.6        1.63        0             1.12             0  
20     76.9       68.5        1.22        0             0.36             0  
29     76.5       68.7        8.05        0             3.32             0  
30     79.7       72.0        2.63        0             0.86             0  
31     77.4       70.4        4.75        0             1.23             0  
41     79.0       69.3        2.03        0             1.02             0  
42     77.7       69.9        3.36        0             0.78             0  
43     78.1       69.3        2.07        0             0.78             0  
53     75.1       66.7        1.07        0             0.36             0  
54     82.9       73.8        2.04        0             0.70             0  
55     79.5       71.9        6.86        0             4.15             0  
56     70.0       62.2        6.96        0             3.89             0  
65     80.7       70.9        4.59        0             1.36             0  
66     80.5       72.3        3.54        0             1.19             0  
67     80.0       71.1        1.40        0             0.47             0  
68     72.1       64.1        3.45        0             1.46             0  
78     78.4       70.4        6.06        0             2.33             0

# Question 2
## Part a
Read the student_data file provided into Python (take note of the file extension to use 
the appropriate pandas reader to read the data).  Drop the first empty column in Python 
and assign the DataFrame to a variable student_data.  

In [15]:
# Load the student data file
student_data = pd.read_excel('student_data.xlsx').drop(columns = ['Unnamed: 0'])
student_data.columns = ['ice_cream_flavor', 'math', 'reading', 'science']

# Clean the values of ice_cream_flavor for later
student_data['ice_cream_flavor'] = student_data['ice_cream_flavor'].replace(['chocollate '],'chocolate')

# Display the data
student_data.head()

ice_cream_flavor  math  reading  science
0          vanilla    90       82       90
1        chocolate   100       73       92
2          vanilla    80       92       95
3      strawberry     95      100       82
4      strawberry     90       79       81

## Part b
The student_data shows the different midterm scores of students in math, reading and 
science, and their favorite ice cream flavors. Select the data in the ice_cream_flavor 
column and convert the flavors to a numpy array, then assign it to a variable called 
flavor. From the student_data, select the math, reading and science scores all at once 
and convert the selected data to a numpy array and assign it to a variable called scores. 
Print the data in the flavor and scores arrays. 

In [16]:
# Assign the columns to a numpy array
flavor = student_data['ice_cream_flavor'].to_numpy()
scores = student_data[['math', 'reading', 'science']].to_numpy()

# Print the data in the arrays
print(flavor)
print(scores)

['vanilla' 'chocolate' 'vanilla' 'strawberry ' 'strawberry ' 'chocolate'
 'vanilla' 'vanilla' 'chocolate' 'chocolate' 'vanilla' 'strawberry '
 'strawberry ' 'chocolate' 'vanilla' 'vanilla']
[[ 90  82  90]
 [100  73  92]
 [ 80  92  95]
 [ 95 100  82]
 [ 90  79  81]
 [ 90  90  90]
 [100  89  91]
 [ 80  85  79]
 [ 85  99  85]
 [100  73  92]
 [ 80  92  95]
 [ 95 100  82]
 [ 90  79  81]
 [ 86  92  90]
 [100  89  89]
 [ 83  95  79]]


## Part c
Use the scores and flavor arrays to slice out the scores where the flavor is chocolate 
only. 

In [193]:
scores[np.where(flavor == 'chocolate')]

array([[100,  73,  92],
       [ 90,  90,  90],
       [ 85,  99,  85],
       [100,  73,  92],
       [ 86,  92,  90]])

## Part d
Use the scores and flavor arrays to slice out the scores where the flavor is chocolate OR 
vanilla. 

In [194]:
scores[np.where((flavor == 'chocolate') | (flavor == 'vanilla'))]

array([[ 90,  82,  90],
       [100,  73,  92],
       [ 80,  92,  95],
       [ 90,  90,  90],
       [100,  89,  91],
       [ 80,  85,  79],
       [ 85,  99,  85],
       [100,  73,  92],
       [ 80,  92,  95],
       [ 86,  92,  90],
       [100,  89,  89],
       [ 83,  95,  79]])

## Part e
Use the scores and flavor arrays to slice out the scores where the flavor is not chocolate 
(you can use the “~ “sign). 

In [19]:
scores[~(flavor == 'chocolate')]

array([[ 90,  82,  90],
       [ 80,  92,  95],
       [ 95, 100,  82],
       [ 90,  79,  81],
       [100,  89,  91],
       [ 80,  85,  79],
       [ 80,  92,  95],
       [ 95, 100,  82],
       [ 90,  79,  81],
       [100,  89,  89],
       [ 83,  95,  79]])

## Part f
Slice out all math and reading scores where the flavor is chocolate, then compute the 
mean of math and reading scores for this subset (you can use the .mean() method on the 
array and specify the axis parameter value appropriately). 

In [196]:
np.mean(scores[np.where(flavor == 'chocolate')], axis = 0)

array([92.2, 85.4, 89.8])

# Question 3
## Part a
Use the LabelBinarizer() in the sklearn package to transform the ice_cream_flavor 
column in the student_data to dummy variables, then join these dummy variables to the 
student_data and drop the original ice_cream_flavor column. Reassign the resulting 
DataFrame to a variable called student_data_1. Print out the entire student_data_1 
DataFrame 

In [24]:
student_data_1 = pd.concat([pd.DataFrame(lb().fit_transform(student_data['ice_cream_flavor'])), student_data], axis=1)
student_data_1 = student_data_1.drop(columns = ['ice_cream_flavor'])
student_data_1.columns = ['chocolate', 'strawberry', 'vanilla', 'math', 'reading', 'science']

student_data_1

chocolate  strawberry  vanilla  math  reading  science
0           0           0        1    90       82       90
1           1           0        0   100       73       92
2           0           0        1    80       92       95
3           0           1        0    95      100       82
4           0           1        0    90       79       81
5           1           0        0    90       90       90
6           0           0        1   100       89       91
7           0           0        1    80       85       79
8           1           0        0    85       99       85
9           1           0        0   100       73       92
10          0           0        1    80       92       95
11          0           1        0    95      100       82
12          0           1        0    90       79       81
13          1           0        0    86       92       90
14          0           0        1   100       89       89
15          0           0        1    83       95       79

## Part b
Extract the math, reading and science scores and use the StandardScaler() class in the 
sklearn.preprocessing module to standardize these scores, then merge the standardized 
scores to the dummy variables, and call the resulting DataFrame student_data_std. Print 
out the entire student_data_1 DataFrame. 

In [38]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(student_data_1[['math', 'reading', 'science']].values)
student_data_std = pd.concat([student_data_1[['chocolate', 'strawberry', 'vanilla']],pd.DataFrame(scaled_data)], axis = 1)
student_data_std.columns = ['chocolate', 'strawberry', 'vanilla', 'math', 'reading', 'science']
student_data_std

chocolate  strawberry  vanilla      math   reading   science
0           0           0        1 -0.034524 -0.709277  0.536906
1           1           0        0  1.346430 -1.762225  0.902459
2           0           0        1 -1.415477  0.460665  1.450789
3           0           1        0  0.655953  1.396618 -0.925306
4           0           1        0 -0.034524 -1.060260 -1.108083
5           1           0        0 -0.034524  0.226676  0.536906
6           0           0        1  1.346430  0.109682  0.719683
7           0           0        1 -1.415477 -0.358295 -1.473636
8           1           0        0 -0.725001  1.279624 -0.376977
9           1           0        0  1.346430 -1.762225  0.902459
10          0           0        1 -1.415477  0.460665  1.450789
11          0           1        0  0.655953  1.396618 -0.925306
12          0           1        0 -0.034524 -1.060260 -1.108083
13          1           0        0 -0.586905  0.460665  0.536906
14          0           0        1  1.346430  0.109682  0.354130
15          0           0        1 -1.001191  0.811647 -1.473636

## Part c
Using a split ratio of 70:30, spit the student_data_1 into training and test set. Reference 
the input and output of the training set as X_train and y_train respectively. Also reference 
the input and output of the test set as X_test and y_test respectively. Print X_train, 
y_train, X_test and y_test. 

In [39]:
X = student_data_std.drop(columns = 'science')
y = student_data_std['science']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3)

In [40]:
X_train

chocolate  strawberry  vanilla      math   reading
5           1           0        0 -0.034524  0.226676
10          0           0        1 -1.415477  0.460665
2           0           0        1 -1.415477  0.460665
8           1           0        0 -0.725001  1.279624
7           0           0        1 -1.415477 -0.358295
13          1           0        0 -0.586905  0.460665
11          0           1        0  0.655953  1.396618
15          0           0        1 -1.001191  0.811647
6           0           0        1  1.346430  0.109682
0           0           0        1 -0.034524 -0.709277
9           1           0        0  1.346430 -1.762225

In [41]:
y_train

5     0.536906
10    1.450789
2     1.450789
8    -0.376977
7    -1.473636
13    0.536906
11   -0.925306
15   -1.473636
6     0.719683
0     0.536906
9     0.902459
Name: science, dtype: float64

In [42]:
X_test

chocolate  strawberry  vanilla      math   reading
3           0           1        0  0.655953  1.396618
14          0           0        1  1.346430  0.109682
1           1           0        0  1.346430 -1.762225
4           0           1        0 -0.034524 -1.060260
12          0           1        0 -0.034524 -1.060260

In [43]:
y_test

3    -0.925306
14    0.354130
1     0.902459
4    -1.108083
12   -1.108083
Name: science, dtype: float64

## Part d
Using the boston_1 DataFrame in question 1a, select the LowTemp, HighTemp, 
WarmestMin, ColdestHigh, AveMin, AveMax columns and use the “pipeline” 
functionality in sklearn to transform the selected data using the MinMaxScalar() and 
Imputer() classes.  With the Imputer() class, the missing data in each column should be 
imputed using the mean value for the column. Assign the resulting DataFrame to a 
variable called pipeline_data. Print the pipeline_data

In [44]:
test = pd.merge(boston_1, more_variables, left_index=True, right_index=True)
X_train_test, X_test_test, y_train_test, y_test_test = train_test_split(X, y, test_size=.3)
test

Month  Year  LowTemp  HighTemp  WarmestMin  ColdestHigh  AveMin  AveMax  \
0        1  1920     -8.0      48.0        37.0         12.0    12.5    29.5   
1        2  1920     -7.0      52.0        34.0         16.0    20.6    34.6   
2        3  1920     10.0      72.0        45.0         25.0    30.5    48.0   
3        4  1920     26.0      67.0        46.0         37.0    38.0    52.1   
4        5  1920     36.0      86.0        61.0         45.0    47.5    61.8   
..     ...   ...      ...       ...         ...          ...     ...     ...   
295      8  1944     53.0     101.0        76.0         69.0    65.1    84.3   
296      9  1944     42.0      90.0        70.0         59.0    57.3    72.7   
297     10  1944     30.0      86.0        64.0         45.0    45.4    62.1   
298     11  1944     29.0      69.0        48.0         35.0    36.1    50.2   
299     12  1944      8.0      50.0        36.0         20.0    23.4    38.2   

     meanTemp  TotPrecip TotSnow  Max24hrPrecip Max24hrSnow  
0        21.0       2.72    24.8           0.74         6.7  
1        27.6       4.11    32.5           1.01        12.2  
2        39.3       3.72      11           1.15           6  
3        45.1       5.68       2           1.19           2  
4        54.6       5.26       0           3.23           0  
..        ...        ...     ...            ...         ...  
295      74.7       1.79       0           1.05           0  
296      65.0       5.36       0           2.46           0  
297      53.7       2.58       0           1.78           0  
298      43.2       5.68     1.2           2.17         1.2  
299      30.8       2.83    10.7           0.83         3.8  

[300 rows x 13 columns]

In [54]:
pipe = Pipeline([('scaler', MinMaxScaler()), 
                  ('impuputer', SimpleImputer(missing_values=np.nan, strategy='mean'))])

In [57]:
test_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('std_scaler', StandardScaler())
])

num_transformed = test_pipe.fit_transform(test.to_numpy())

ValueError: Cannot use median strategy with non-numeric data:
could not convert string to float: 'NR'

In [59]:
test[test.eq("NR").any(1)]

Month  Year  LowTemp  HighTemp  WarmestMin  ColdestHigh  AveMin  AveMax  \
112      5  1929     42.0      96.0        72.0         48.0    50.0    71.9   
113      6  1929     45.0      94.0        72.0         61.0    59.0    77.6   
114      7  1929     54.0      94.0        75.0         69.0    62.9    82.2   
115      8  1929     54.0      90.0        69.0         67.0    60.1    78.4   
116      9  1929     40.0      97.0        71.0         58.0    56.7    73.8   
117     10  1929     34.0      78.0        54.0         46.0    44.5    61.9   
124      5  1930     45.0      95.0        71.0         50.0    51.1    68.3   
125      6  1930     45.0      95.0        71.0         65.0    62.8    81.9   
126      7  1930     58.0      94.0        74.0         71.0    64.9    80.7   
127      8  1930     53.0      98.0        76.0         66.0    62.6    78.4   
128      9  1930     49.0      91.0        72.0         68.0    60.3    78.5   
129     10  1930     34.0      87.0        58.0         43.0    45.5    60.5   

     meanTemp  TotPrecip TotSnow  Max24hrPrecip Max24hrSnow  
112      61.0       2.82      NR           0.86          NR  
113      68.3       2.30      NR           0.68          NR  
114      72.6       1.35      NR           0.64          NR  
115      69.2       2.22      NR           1.16          NR  
116      65.3       0.76      NR           0.16          NR  
117      53.2       2.38      NR           1.94          NR  
124      59.7       3.39      NR           1.06          NR  
125      72.4       2.24      NR           0.76          NR  
126      72.8       3.36      NR           1.16          NR  
127      70.5       3.03      NR           1.90          NR  
128      69.4       0.22      NR           0.13          NR  
129      53.0       5.29      NR           3.23          NR

## Part e
Output the descriptive statistics of the pipeline_data including mean, median, variance, 
minimum value, maximum value, variance, standard deviation and skewness. You can 
use the .apply() functionality of the pandas DataFrame.